<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Registered;
use Illuminate\Support\Facades\Mail;
use App\Mail\RegistradosEmail;
use App\Inscritos;
use Illuminate\Support\Facades\Auth;
use App\User;

class RegistradosController extends Controller
{
    //

    public function searchRegistered (Request $request){

        $student = Registered::where('dni',$request->code)->first();

        if(isset($student->tipo_inscripcion)){

            switch ($student->tipo_inscripcion){

                case 'estudiante_esis':
                    $inscrito = Inscritos::where('codigo',$student->dni)->first();
                    if($inscrito){
                        $student->institucion = $inscrito->institucion;
                    }
                    break;
                default:
                    break;

            }
        }else{

            $student = Inscritos::where('dni',$request->code)->first();

        }

        return response()->json($student);

    }
    public function renderReportTable()
    {

   //$students = Registered::where('pago','50');
      $students = Registered::all();

//        return response()->json($students);

        return view('backend.registrados.report', compact('students'));
    }

    public function registradosData()
    {

        $students = Registered::all();
        return response()->json($students);

    }

    public function llenar()
    {
        $datos = new Registered;
        $datos->dni = '2013-39077';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MARIACA CHOQUE';
        $datos->nombre = 'EDDY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-111007';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ZARATE ROMERO';
        $datos->nombre = 'IAN NATHANIEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119022';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'RAMOS VELASCO';
        $datos->nombre = 'TONNY WASHINGTON';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119041';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'TORRES CALDERON';
        $datos->nombre = 'WILLIAM GRABRIEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119052';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'UCHARICO MAQUERA';
        $datos->nombre = 'GUILLERMO ENRIQUE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119056';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ROMERO GUTIERREZ';
        $datos->nombre = 'BRAYAN ANDRES';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119059';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CENTENO ALARCON';
        $datos->nombre = 'STEVIE ALBERTH';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119065';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LLANQUE LLANQUE';
        $datos->nombre = 'JUAN CARLOS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119007';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'FLORES ARRATIA';
        $datos->nombre = 'CESAR ENRIQUE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119008';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CANQUE CHAMBI';
        $datos->nombre = 'MILTON JAVIER';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119009';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PEREZ CRUZ';
        $datos->nombre = 'ANIBAL MARCELO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119013';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'APAZA OCHOA';
        $datos->nombre = 'JOSE ANGEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119014';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'GOMEZ CALIZAYA';
        $datos->nombre = 'DAYAN HUGO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119016';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'HUALLPA ROSA';
        $datos->nombre = 'DAVIS LEONEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119017';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LOZA QUISPE';
        $datos->nombre = 'IVAN GUSTAVO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119019';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'FLORES MANRIQUE';
        $datos->nombre = 'FERNANDO MOISES';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119022';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LIMACHI LIPE';
        $datos->nombre = 'ROY FRANCISCO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119027';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CALIZAYA MAMANI';
        $datos->nombre = 'VANESSA DEL ROSARIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119030';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ROND�N PUMA';
        $datos->nombre = 'FERNANDO MARCIAL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119031';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MARCA MAMANI';
        $datos->nombre = 'JACKELIN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119033';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'HANAMPA MIRANDA';
        $datos->nombre = 'JUAN CARLOS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119035';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHATA ARO';
        $datos->nombre = 'LISBETH YAKELIN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119038';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDORI PERALTA';
        $datos->nombre = 'WALTER GUSTAVO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119042';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ARGANDO�A TICONA';
        $datos->nombre = 'EDISSON ANGEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119043';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'HUALLPA LLUNCO';
        $datos->nombre = 'EDSON JESUS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119045';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'GONZALES CONISLLA';
        $datos->nombre = 'ANDY FABRICIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119049';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHURA PERALTA';
        $datos->nombre = 'CRISTIAN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119050';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDORI FLORES';
        $datos->nombre = 'JUAN LUIS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119054';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CASTRO CACERES';
        $datos->nombre = 'JOSE ANGEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119057';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'GUTI�RREZ OTAZ�';
        $datos->nombre = 'GABRIEL LUDWIG';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119058';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PARI VI�A';
        $datos->nombre = 'DIEGO EDWARD';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119059';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'QUISPE LEVA';
        $datos->nombre = 'EDDY ALEXIS JOSIAS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119061';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CALISAYA BARRETO';
        $datos->nombre = 'JORGE LUIS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119062';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'RAMOS VASQUEZ';
        $datos->nombre = 'CARLOS JUNIOR';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119063';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MARCA MACHACA';
        $datos->nombre = 'BRANDO EFRAIN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119065';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDE ESCOBAR';
        $datos->nombre = 'JEUS MOISES';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119066';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MIRELES BERNAB�';
        $datos->nombre = 'VICTOR FERNANDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119067';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PANIAGUA MACHACA';
        $datos->nombre = 'ERICK JUNIOR';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119069';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'INFANTAS CAHUANA';
        $datos->nombre = 'BRYAN DAVID';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119071';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHOQUEZA HUAICANI';
        $datos->nombre = 'RICHARD OLIGARIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119001';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'GARC�A PAREDES';
        $datos->nombre = 'DAVID AVELINO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119003';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'YANAPA CHICALLA';
        $datos->nombre = 'ALEJANDRO DANIEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119004';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'QUISPE YANAPA';
        $datos->nombre = 'LUIS ORLANDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119005';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHIQUE CURMILLUNI';
        $datos->nombre = 'DANIEL RODRIGO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119006';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'TARQUI ROND�N';
        $datos->nombre = 'RICHARD DANIEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119007';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'FLORES VALERIANO';
        $datos->nombre = 'JOEL JESUS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119009';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'COPARI COPAJA';
        $datos->nombre = 'YUNIOR';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119010';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'GONZALES MAMANI';
        $datos->nombre = 'YEFERSON';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119011';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'SAIRA MAMANI';
        $datos->nombre = 'RIBALDO IGNACIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119014';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI ROSADO';
        $datos->nombre = 'FREDD';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119016';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'QUISPE OCHOA';
        $datos->nombre = 'JOHAN DAVID';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119017';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'COAYLA ALVES';
        $datos->nombre = 'OBED VLADIMIR';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119018';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'DE LA CRUZ CHOQUE';
        $datos->nombre = 'RODRIGO MART�N';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119019';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'DE LA CRUZ CHOQUE';
        $datos->nombre = 'RICARDO MIGUEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119020';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'INQUILLA VELA';
        $datos->nombre = 'RUNI';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119021';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'APAZA CONDE';
        $datos->nombre = 'DIEGO LEONARDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119022';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ARUCUTIPA CAMA';
        $datos->nombre = 'KHEYVIN DERLIZ';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119023';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CAXI AROCUTIPA';
        $datos->nombre = 'KEV�N DIXON';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119024';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHANINI MENA';
        $datos->nombre = 'FRANZ';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119025';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHOQUEHUAYTA QUENTA';
        $datos->nombre = 'JULIO C�SAR';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119026';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONISLLA MARTINEZ';
        $datos->nombre = 'FABI�N ALEXIS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119027';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'G�MEZ CONDORI';
        $datos->nombre = 'JEAN CARLO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119028';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'HUANQUI CORNEJO';
        $datos->nombre = 'PEDRO ENRIQUE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119029';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'INCHU�A SEQQUERA';
        $datos->nombre = 'ROBERTO CARLOS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119030';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAQUERA VILCARANA';
        $datos->nombre = 'JHONATAN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119031';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MELCHOR ROSAS';
        $datos->nombre = 'R�MEL NELSON ROY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119032';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MIRANDA FLORES';
        $datos->nombre = 'JOSU� SEBASTI�N';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119033';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'AROCUTIPA LOPE';
        $datos->nombre = 'RICHARD REYES';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119034';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'COHAILA AQUINO';
        $datos->nombre = 'YANELI SUGUEY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119035';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ESPINOZA CHIPANA';
        $datos->nombre = 'ALEXIS GIOSUE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119036';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'HUANCA HUANACUNE';
        $datos->nombre = 'EDDY ELISSON';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119037';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'HUAYCANI G�MEZ';
        $datos->nombre = 'KATHERINE LILIANA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119038';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI ACHO';
        $datos->nombre = 'YORDAN JES�S';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119039';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI VALDEZ';
        $datos->nombre = 'HELTON FABRIZIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119040';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'POLLOQUERI UCHASARA';
        $datos->nombre = 'LEONARDO BRAYAN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119041';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'QUINTO HUANCA';
        $datos->nombre = 'ANGEL SEBASTIAN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119043';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ARZOLA ROMERO';
        $datos->nombre = 'JESSE NAOMI';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119044';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CASTILLO SANCA';
        $datos->nombre = 'CRISTHIAN SANTOS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119045';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CCAMA CCAMA';
        $datos->nombre = 'ELIO YASMANI';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119046';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHOQUE CHOQUEGONZA';
        $datos->nombre = 'LUCIO FERNANDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119047';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHOQUE HUANCA';
        $datos->nombre = 'M�NICA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119048';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'FLORES PARI';
        $datos->nombre = 'JUAN ALBERTO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119049';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'GUERREROS HUANCA';
        $datos->nombre = 'CINTHYA PAOLA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119050';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LAURA LLANOS';
        $datos->nombre = 'ERICA LISBETH';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119051';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'RODRIGUEZ DEL CARPIO';
        $datos->nombre = 'GIANCARLO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119052';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'TURPO APAZA';
        $datos->nombre = 'FRANK V�THALY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119053';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'VILLACA MAMANI';
        $datos->nombre = 'ANYERSON IVAN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119054';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ALIAGA YANARICO';
        $datos->nombre = 'MIJAEL AXEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119055';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'BERNABE CUTIPA';
        $datos->nombre = 'KEVIN DANIEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119056';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHAGUA MONTUFAR';
        $datos->nombre = 'CRISTIAN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119057';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHAMBILLA PERCA';
        $datos->nombre = 'RICARDO MAURICIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119058';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDO CONDO';
        $datos->nombre = 'ROSA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119059';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDORI MAMANI';
        $datos->nombre = 'DEYBIT ANTHONY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119060';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDORI P�REZ';
        $datos->nombre = 'ERICK FERNANDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119061';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'FLORES G�MEZ';
        $datos->nombre = 'MAURICIO JOS�';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119062';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'GUTI�RREZ CUTIPA';
        $datos->nombre = 'ROLANDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119063';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'JORDAN RAMOS';
        $datos->nombre = 'AXEL JES�S';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119064';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MARON PAREDES';
        $datos->nombre = 'PATRICK ANTHONY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119065';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PADILLA BACAS';
        $datos->nombre = 'LUIS BENITO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119066';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PERALTA VILLEGAS';
        $datos->nombre = 'PATRICK ARIEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119067';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'QUISPE PARI';
        $datos->nombre = 'GONZALO FABRIZIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119068';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'RAMIREZ MAMANI';
        $datos->nombre = 'JOSE CARLOS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2018-119070';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'VASQUEZ MIJA';
        $datos->nombre = 'JAMPIER SMITH';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2012-36178';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'JORGES MEDINA';
        $datos->nombre = 'RODRIGO DANIEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2012-36185';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'RAMIREZ LLANO';
        $datos->nombre = 'NESTOR RENE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39051';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDORI MONTOYA';
        $datos->nombre = 'VICTOR HUGO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119020';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHOQUETARQUI MESTAS';
        $datos->nombre = 'HABRAM JORGE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119059';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'POMA CONDORI';
        $datos->nombre = 'DIANA ALEXANDRA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119015';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CASTRO VARGAS';
        $datos->nombre = 'MAYRA ALEXANDRA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119016';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'COPAJA SOTO';
        $datos->nombre = 'RENZO ITHALO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119027';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'VILCA PINTO';
        $datos->nombre = 'MIGUEL ANGEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119031';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'SALCEDO CHATA';
        $datos->nombre = 'DANIEL  HUGO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119034';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MALLEA MAMANI';
        $datos->nombre = 'WALTER RENATO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119058';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MACHACA CONDE';
        $datos->nombre = 'LIZ GRICEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119067';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'RIVERA MENDOZA';
        $datos->nombre = 'JHONNY ANGELES';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119002';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'QUISPE FLORES';
        $datos->nombre = 'DANNA MICHELLE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119003';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'SEGOVIA HINOJOSA';
        $datos->nombre = 'JAMES ENRIQUE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119005';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'VILLANUEVA MAMANI';
        $datos->nombre = 'PIERO SEBASTIAN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119006';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CRUZ HUACCHO';
        $datos->nombre = 'JUAN JOSE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119010';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MORENO RAMOS';
        $datos->nombre = 'ANTONI MARIANO FRANCISCO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119011';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ZARATE ROBLES';
        $datos->nombre = 'YOJAN EDWUAR';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119012';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'JIMENEZ MENDOZA';
        $datos->nombre = 'JAVIER ALEX';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119021';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHAMBI LAQUI';
        $datos->nombre = 'BRYAN RICHARD';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119023';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI JIMENEZ';
        $datos->nombre = 'RICHARD WALTER';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119024';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ACERO MAMANI';
        $datos->nombre = 'NAIN NEPTALI';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119025';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MIRANDA POMA';
        $datos->nombre = 'MILAGROS ESTEFANY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119026';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'OSCO OSNAYO';
        $datos->nombre = 'JOSH PAUL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119028';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'HUANCO TICONA';
        $datos->nombre = 'BRAYAN FERNANDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119029';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ALANOCA VILCA';
        $datos->nombre = 'JHENDER ANDRE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119032';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'V�SQUEZ PARI';
        $datos->nombre = 'JES�S EDWIN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119036';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MOLLOCONDO RAMOS';
        $datos->nombre = 'BRYAM ALFREDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119037';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PACO SUCA';
        $datos->nombre = 'ERIKA JUDITH';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119041';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ALANOCA CH�VEZ';
        $datos->nombre = 'MIGUEL STEFANO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119048';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'FLORES GONZALO';
        $datos->nombre = 'RENATO FRANCO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119051';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ESCOBAR CHURA';
        $datos->nombre = 'WYLLIAM FERNANDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119052';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PAXI LAURA';
        $datos->nombre = 'JUAN SANTOS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119055';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'GUILLERMO MAMANI';
        $datos->nombre = 'ORLANDO SERGIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119056';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PEREZ CHECALLA';
        $datos->nombre = 'ELVIS JHONATAN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2017-119070';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ENCINAS QUISPE';
        $datos->nombre = 'ALBERTH ANTHONY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39091';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI MAMANI';
        $datos->nombre = 'HEBER';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '1994-12782';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MIRANDA CARRILLO';
        $datos->nombre = 'RICHARD JAVIER';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2007-30794';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAYTA YUCRA';
        $datos->nombre = 'WILLIANS LUCIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2010-35531';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'AGUIRRE VARGAS';
        $datos->nombre = 'MARVIN ANTHONY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2011123008';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'GINEZ PAYE';
        $datos->nombre = 'GERMAN JUNIOR';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2012-36146';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAQUERA COHAILA';
        $datos->nombre = 'JHONATAN JORDANO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39048';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'BONIFACIO CONDORI';
        $datos->nombre = 'RUMY YHONSSON';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39090';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LUQUE ROJAS';
        $datos->nombre = 'SAUL RENATO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119001';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LINARES ROJAS';
        $datos->nombre = 'CATHERINE JASMINE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119006';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LUQUE VELASQUEZ';
        $datos->nombre = 'VICTOR DAMIAN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119012';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDORI MAMANI';
        $datos->nombre = 'FREDDY ROBERT';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119030';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MEDINA LUPO';
        $datos->nombre = 'HAROLD JOEL FRANSUA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119031';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'HUANCA CARITA';
        $datos->nombre = 'ROGER YHONNY JOEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119006';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CUEVA CHAMBILLA';
        $datos->nombre = 'CHRISTIAN MANUEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119009';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI SALAMANCA';
        $datos->nombre = 'BRAYAN LUI';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119010';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'APAZA CARITA';
        $datos->nombre = 'EDENIO LEONIDAS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119015';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'APAZA ATENCIO';
        $datos->nombre = 'JUAN PABLO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119029';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDORI MAMANI';
        $datos->nombre = 'EDUARDO FRANCISCO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119033';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDORI HUISA';
        $datos->nombre = 'LUIS ANGEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119039';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LLANOS TICONA';
        $datos->nombre = 'JOHNNY EDGARDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119041';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHOQUE CHILE';
        $datos->nombre = 'CRISTIAN ELVIS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119042';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MELGAREJO NIETO';
        $datos->nombre = 'TONY BRYAN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119045';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'QUISPE HUACANI';
        $datos->nombre = 'EDDY ANTONI';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119052';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'SOSA YABAR';
        $datos->nombre = 'GONZALO LIZANDRO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119055';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'AGUILAR BARRIENTOS';
        $datos->nombre = 'JULIO ISRRAEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119062';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'BERNABE HUARCUSI';
        $datos->nombre = 'VERONICA DEL CARMEN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119002';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ESPINOZA BALCONA';
        $datos->nombre = 'MARCO ANTONIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119003';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ESQUIVEL ROQUE';
        $datos->nombre = 'SHIRLEY EDITH';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119005';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LUPACA LUPACA';
        $datos->nombre = 'FRANK';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119006';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI ACERO';
        $datos->nombre = 'JHORDY ESIDIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119010';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'TAPIA RAMOS';
        $datos->nombre = 'PERCY RODRIGO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119014';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'NINA REYNA';
        $datos->nombre = 'GERALDINE DEL ROSARIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119017';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MARTINEZ CONDORI';
        $datos->nombre = 'ANDRES ALBERTO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119018';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'L�PEZ VALERA';
        $datos->nombre = 'BRENDA BRIGITTE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119020';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'POMA CATARI';
        $datos->nombre = 'JOSE RODRIGO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119021';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LAQUI CABRERA';
        $datos->nombre = 'JORDAN  FRIDMAN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119024';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHAC�N ALVAREZ';
        $datos->nombre = 'MIRYAM ELIZABETH';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119025';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ZARATE CORI';
        $datos->nombre = 'LIZBETH FIORELLA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119028';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'NINA ESTRADA';
        $datos->nombre = 'LUIS ALBERTO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119029';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ACERO ZAPANA';
        $datos->nombre = 'ELMER BONIFACIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119030';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHAVEZ CONDORI';
        $datos->nombre = 'HEYDI H�LLARY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119035';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CUTIPA APAZA';
        $datos->nombre = 'BRIAM ANTHONY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119036';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'FLORES VILCA';
        $datos->nombre = 'MORONI DERLYZ ROMAN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119037';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI ROMERO';
        $datos->nombre = 'FRANKLYN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119039';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'TICONA FLORES';
        $datos->nombre = 'ALVARO HUGO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119042';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'TESILLO GOMEZ';
        $datos->nombre = 'LIZBETH LUZ';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119045';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PIZARRO QUISPE';
        $datos->nombre = 'ROGER GROVE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119047';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PINO PAXI';
        $datos->nombre = 'MARISOL NAIT';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119048';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'COLOMA QUISPE';
        $datos->nombre = 'ERIK GIOVANNI';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119049';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI QUISPE';
        $datos->nombre = 'DARYL ANGEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119050';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'HUACCA ENCINAS';
        $datos->nombre = 'LUIS ALBERTO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119051';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CANDIA AGUILAR';
        $datos->nombre = 'ELMER ABDON';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119053';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PARI MACHACA';
        $datos->nombre = 'JHEFERSON STING';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119055';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDORI JOAQUIN';
        $datos->nombre = 'RODY FRANKLIN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119057';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LIMA PACCA';
        $datos->nombre = 'LUIS RODOLFO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119061';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PARIA QUISPE';
        $datos->nombre = 'ADRIAN ALEX';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119062';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'HINOJOSA MUCHO';
        $datos->nombre = 'JHONATAN ALEXANDER';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2016-119064';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI CATACORA';
        $datos->nombre = 'DAYSI MARIA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2010-35559';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'HERENCIA VICENTE';
        $datos->nombre = 'JUAN VICTOR JOSEPH';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2012-36181';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MORALES CABALLERO';
        $datos->nombre = 'ALVARO ANDERSON';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39050';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDORI SUCASACA';
        $datos->nombre = 'EDWIN DAVID';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39059';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CATARI PACCORICUNA';
        $datos->nombre = 'WALTER LUIS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39073';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CAMA CHURA';
        $datos->nombre = 'JUAN CARLOS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39074';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CCALLI CCALLI';
        $datos->nombre = 'JESUS ANGEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39078';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'NEYRA MELCHOR';
        $datos->nombre = 'LUIS ANTONIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39107';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PACCI VARGAS';
        $datos->nombre = 'ROOSSELVET YOCERO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119004';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PARRA OLARTE';
        $datos->nombre = 'EDGARDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119018';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHACALIAZA SALAZAR';
        $datos->nombre = 'CESAR JEAN PIERRE';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119025';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'VEL�SQUEZ CURI';
        $datos->nombre = 'ALEJANDRO RUB�N';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119027';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'TURPO LUQUE';
        $datos->nombre = 'ALEXZANDER EMANUEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119043';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'QUINTO APAZA';
        $datos->nombre = 'YULISA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119064';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ESTRADA CRUZ';
        $datos->nombre = 'DIEGO ALEXANDER';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119067';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ANCHAPURI CATACHURA';
        $datos->nombre = 'JULIO CESAR';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119001';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'RAMIREZ REJAS';
        $datos->nombre = 'RUTH DE JESUS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119003';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ALVARADO ACHATA';
        $datos->nombre = 'JHON';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119005';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'SINTECALA MULLUNI';
        $datos->nombre = 'JAKELYN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119007';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'AYCAYA ALANIA';
        $datos->nombre = 'ERICK JOEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119011';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LAURA PAXI';
        $datos->nombre = 'ROSA ANGELA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119013';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDORI CABRERA';
        $datos->nombre = 'DIEGO ARMANDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119014';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PONGO CCAMA';
        $datos->nombre = 'RICHARD CECILIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119023';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'SANCA PADILLA';
        $datos->nombre = 'LIZETH DIANA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119025';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MEDINA CUSSI';
        $datos->nombre = 'EDUARDO DANIEL SAMUEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119028';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PACCO CONCORI';
        $datos->nombre = 'ELVIS RUBEN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119030';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CONDORI CATUNTA';
        $datos->nombre = 'ALEXIS JOHER';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119031';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ZEVALLOS GOMEZ';
        $datos->nombre = 'MARIA FERNANDA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119032';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MENDOZA CHINO';
        $datos->nombre = 'JHON WILBER';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119034';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI CARIAPAZA';
        $datos->nombre = 'JOSUE ALDAIR';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119035';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHOQUE MAQUERA';
        $datos->nombre = 'MARCO ANTONIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119037';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'HUAYNAPATA AGUILAR';
        $datos->nombre = 'WALTER DANIEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119038';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'RAMOS VALD�Z';
        $datos->nombre = 'LEANDRO ANDR�';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119043';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'RAMOS HUANCA';
        $datos->nombre = 'FRESSIA EMMY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119046';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PUMA MARCA';
        $datos->nombre = 'WILLIAMS JACK';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119048';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'JUANILLO CALDERON';
        $datos->nombre = 'DENNIS MITCHELL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119054';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'FLORES YANCE';
        $datos->nombre = 'JES�S JOSEPH';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119063';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI HUALPA';
        $datos->nombre = 'DALTHON';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119065';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'FRISANCHO PONCE';
        $datos->nombre = 'ALBERTH RONALDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2015-119066';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CERVANTES TAPIA';
        $datos->nombre = 'JESUS JAROL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2012-36153';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHOQUE CUYO';
        $datos->nombre = 'ANGEL SALVADOR';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2012-36161';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAQUERA SACACA';
        $datos->nombre = 'ABEL JHANO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2012-36732';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ALCAZAR RAMOS';
        $datos->nombre = 'MILAGROS PAMELA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39049';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'COAQUIRA MACHACA';
        $datos->nombre = 'KAREN MELBA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39064';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI LLANOS';
        $datos->nombre = 'JHOJAN GIANMARCO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39072';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CAHUAPAZA HILASACA';
        $datos->nombre = 'SUSAN RUTH';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39085';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHIPANA HUARCUSI';
        $datos->nombre = 'JHON KEVIN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39092';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ORDO�O MUSAJA';
        $datos->nombre = 'KILMER ROMARIO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2013-39103';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'COLQUE CONDORI';
        $datos->nombre = 'BRENDA VICTORIA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119002';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'PONGO CONDORI';
        $datos->nombre = 'ROBERTO CARLOS';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119003';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'JOAQUIN RAMIREZ';
        $datos->nombre = 'GIANCARLO BRAYAM';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119008';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'YUFRA SUAREZ';
        $datos->nombre = 'ARIEE BELEN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119009';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'AYALA ALANOCA';
        $datos->nombre = 'STEVEN PHILIP';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119010';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'TICONA CHURA';
        $datos->nombre = 'DANIEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119011';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI MAMANI';
        $datos->nombre = 'MIRIAM MARISOL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119013';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CUTIMBO CENTON';
        $datos->nombre = 'KATHERINE PAOLA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119014';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'APAZA DELGADO';
        $datos->nombre = 'ROCIO STHEFANNY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119015';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'TUYO BERNAL';
        $datos->nombre = 'FERNANDO JES�S';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119016';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHIPANA MOLLO';
        $datos->nombre = 'YERSSON ANGEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119021';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LIMACHE MAYTA';
        $datos->nombre = 'LUDWIG ANGEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119022';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ESPINAL AQUINO';
        $datos->nombre = 'ALVIN ANDONI';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119024';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'GARCIA IQUISE';
        $datos->nombre = 'ALEXANDRA LUCIANA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119029';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'BUTRON PARIHUANA';
        $datos->nombre = 'RICHARD RODRIGO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119033';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHOQUE ORTIGOZO';
        $datos->nombre = 'ALDO JORDAN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119038';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'MAMANI SI�A';
        $datos->nombre = 'ARACELY DANITZA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119042';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'GINES COLANA';
        $datos->nombre = 'MILCA SARAY';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119045';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ALANOCA ANAHUA';
        $datos->nombre = 'ZARITA GLORIA';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119048';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'LAQUI FLORES';
        $datos->nombre = 'ISAIAS YENCIN';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119050';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'HERNANDEZ RAMOS';
        $datos->nombre = 'ALEXANDER EDUARDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119051';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'VIVEROS CORDOVA';
        $datos->nombre = 'JHAIR RODRIGO EDUARDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119057';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'CHIRE LLANQUI';
        $datos->nombre = 'JOEL ANTONI';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119062';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'DAVALOS CHOQUE';
        $datos->nombre = 'GUSTAVO FERNANDO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119063';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'ROQUE COAQUIRA';
        $datos->nombre = 'JUAN DIEGO';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119065';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'COILLO CHAMBILLA';
        $datos->nombre = 'ALEX MANUEL';
        $datos->save();
        $datos = new Registered;
        $datos->dni = '2014-119069';
        $datos->tipo_inscripcion = 'estudiante_esis';
        $datos->apellido = 'VILCA ALANIA';
        $datos->nombre = 'JOEL';
        $datos->save();

    }


    public function confirmateStudent(Request $request)
    {

        $student = Registered::find($request->id);

        switch ($student->tipo_inscripcion) {
            case 'estudiante_esis':
                {
                    $check = Inscritos::where('codigo', $student->dni)
                        ->orWhere('dni', $student->dni)->get();
                    break;
                }

            default:
                {
                    $check = Inscritos::where('dni', $student->dni)->get();
                    break;
                }
        }

        //return response()->json($check);

        if (count($check) > 0) {

            return response()->json(['status' => 'EXIST']);

        }

        $inscrito = new Inscritos;
        $inscrito->last_user_modificied = Auth::id();
        $inscrito->nombre = $student->nombre;
        $inscrito->email = $student->email;
        $inscrito->apellido = $student->apellido;

        switch ($student->tipo_inscripcion) {

            case 'estudiante_esis':
                {
                    $inscrito->tipo_inscripcion = $student->tipo_inscripcion;
                    $inscrito->codigo = $student->dni;
                    $inscrito->institucion = 'UNIVERSIDAD NACIONAL JORGE BASADRE GROHMANN';

                    break;
                }

            default:
                {
                    $inscrito->tipo_inscripcion = $student->tipo_inscripcion;
                    $inscrito->dni = $student->dni;
                    $inscrito->institucion = $student->instituto;

                    break;
                }
        }

        $inscrito->ciudad = $student->ciudad;
        $inscrito->celular = $student->telefono;
        $inscrito->foto_voucher = $student->imagen;

        $inscrito->pago = $student->pago;

        $inscrito->save();

        if ($inscrito->email == null) {
            return response()->json(['status' => 'NOT_EMAIL']);
        }

        //return response()->json(['status' => 'SEND EMAIL']);

        $messageSend = Mail::to($inscrito->email)
            ->send(new RegistradosEmail($inscrito));
        if ($messageSend == null) {
            return response()->json(['status' => 'OK']);
        } else {
            return response()->json(['status' => 'ERROR']);
        }

    }

    public function show(Request $request, $id)
    {
        $id_registered = $id;
        try {
            $registered = Registered::findOrFail($id_registered);
            if (isset($registered->last_user_modificied)) {
                $registered->user = User::findOrFail($registered->last_user_modificied);
            }
            return response()->json($registered);
        } catch (Exception $e) {
            return response()->json('ERROR');
        }
    }

    public function updatePay(Request $request, $id)
    {

        $id_registered = $id;
        $dataResponse = [
            'pago' => $request->payEditPay,
        ];
        try {
            $registered = Registered::find($id_registered);
            $registered->pago = $dataResponse['pago'];
            $registered->save();
            return redirect()->route('report.registrados')
                ->with('status_pay', TRUE);
        } catch (Exception $e) {
            return redirect()->route('report.registrados')
                ->with('error_pay', TRUE);
        }
    }

    public function update(Request $request, $id)
    {
        $id_inscrito = $id;
        $dataResponse = [
            'nombre' => $request->nameEdit,
            'apellido' => $request->lastnameEdit,
            'celular' => $request->celularEdit,
            'dni' => $request->dniEdit,
            'instituto' => $request->instituteEdit,
            'email' => $request->emailEdit,
            'pago' => $request->payEdit,
            'ciudad' => $request->cityEdit,
            'tipo_inscripcion' => $request->typeEdit,
        ];
        try {
            if ($dataResponse['nombre'] == '' || $dataResponse['apellido'] == '') {
                return redirect()->route('report.inscritos')
                    ->with('error', TRUE);
            } else {
                $registered = Registered::find($id_inscrito);
                $registered->nombre = $dataResponse['nombre'];
                $registered->apellido = $dataResponse['apellido'];
                $registered->celular = $dataResponse['celular'];
                $registered->dni = $dataResponse['dni'];
                $registered->instituto = $dataResponse['instituto'];
                $registered->email = $dataResponse['email'];
                $registered->pago = $dataResponse['pago'];
                $registered->ciudad = $dataResponse['ciudad'];
                $registered->tipo_inscripcion = $dataResponse['tipo_inscripcion'];
                $registered->last_user_modificied = Auth::id();
                $registered->save();
                return redirect()->route('report.registrados')
                    ->with('status', TRUE);
            }
        } catch (Exception $e) {
            return redirect()->route('report.registrados')
                ->with('error', TRUE);
        }
    }

}
